// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OY3THV8bNpMMszJa22gG9qQrgrRspIs',
    appId: '1:181208508375:web:ee10ead30320b8b7998d92',
    messagingSenderId: '181208508375',
    projectId: 'learning-ms-37dc0',
    authDomain: 'learning-ms-37dc0.firebaseapp.com',
    storageBucket: 'learning-ms-37dc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCy9aMP5z_Av0DXqImrj0ZeebqE1NkF28',
    appId: '1:181208508375:android:8b6fe8cff10b8177998d92',
    messagingSenderId: '181208508375',
    projectId: 'learning-ms-37dc0',
    storageBucket: 'learning-ms-37dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0xI9VASbb7dCakbrTQOE9UBeqpgmyDAQ',
    appId: '1:181208508375:ios:be8c199837951e8d998d92',
    messagingSenderId: '181208508375',
    projectId: 'learning-ms-37dc0',
    storageBucket: 'learning-ms-37dc0.firebasestorage.app',
    androidClientId: '181208508375-liv0ne4r7fdoftllfd3e8ats9k62uco9.apps.googleusercontent.com',
    iosClientId: '181208508375-jtfum007jjviv136rbhbbvor4sfp60lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.essFms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGcjtoY2hclFtLwT6F-MtGvMW22cnxikA',
    appId: '1:755512017161:ios:d9ca7eef741f29e3bbd3d8',
    messagingSenderId: '755512017161',
    projectId: 'iotcar-9259e',
    databaseURL: 'https://iotcar-9259e-default-rtdb.firebaseio.com',
    storageBucket: 'iotcar-9259e.appspot.com',
    iosBundleId: 'com.example.projectDrone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMAx8lJLo9t_4M-ufstXDu8teLIvYDPXs',
    appId: '1:755512017161:web:a794e523fbe5f65bbbd3d8',
    messagingSenderId: '755512017161',
    projectId: 'iotcar-9259e',
    authDomain: 'iotcar-9259e.firebaseapp.com',
    databaseURL: 'https://iotcar-9259e-default-rtdb.firebaseio.com',
    storageBucket: 'iotcar-9259e.appspot.com',
    measurementId: 'G-3QQECNWV1T',
  );
}